version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      include: "scope"
  
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      minor-and-patch:
        applies-to: "version-updates"
        update-types:
          - "minor"
          - "patch"
      security-updates:
        applies-to: "security-updates"
        update-types:
          - "minor"
          - "patch"
    commit-message:
      prefix: "fix"
      prefix-development: "chore"
      include: "scope"